core/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('firstapp.urls'))
]

firstapp/urls.py
from django.contrib import admin
from django.urls import path 
from firstapp import views #Added manually

app_name = "firstapp"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index , name='index'),
    path("details/" , views.details , name='details')
]

firstapp/models.py
from django.db import models

# Create your models here.

firstapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request , 'firstapp/index.html')


def details(request):
    return render(request , 'firstapp/details.html')

firstapp/templates/firstapp/base.html
{% extends 'firstapp/footer.html' %}

firstapp/templates/firstapp/details.html
{% extends 'firstapp/base.html' %}

{% block content %} 

<div class="d-flex justify-content-center" style="height: 500px;">
    <h2>This is the detail page</h2>

</div>


{% endblock content %}

firstapp/templates/firstapp/footer.html
{% extends 'firstapp/header.html' %}

{% block footer %}
    <footer class="bg-dark text-light">
        <div class="container py-4">
          <div class="row">
            <div class="col-md-6">
              <p>&copy; 2023 Your Company Name. All rights reserved.</p>
            </div>
            <div class="col-md-6 text-md-end">
              <p>
                <i class="fas fa-map-marker-alt me-2"></i> 123 Main Street, City, State, ZIP Code
              </p>
              <p>
                <i class="fas fa-phone-alt me-2"></i> (123) 456-7890
              </p>
              <p>
                <i class="fas fa-envelope me-2"></i> info@yourcompany.com
              </p>
            </div>
          </div>
        </div>
      </footer>

{% endblock footer %}   
      

firstapp/templates/firstapp/header.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js">
    <title>Document</title>
</head>



<body>
    
    <nav class="navbar navbar-expand-lg bg-body-primary bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{%url 'firstapp:index'%}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'firstapp:details'%}">Details page</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Pricing</a>
                    </li>
                   
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}{% endblock content %}
    {% block footer %}{% endblock footer %}
</body>

</html>

firstapp/templates/firstapp/index.html
{% extends 'firstapp/base.html' %}

{% block content %}
<div class="d-flex justify-content-center" style="height: 500px;">
    <h1>This is my index page </h1>
</div>


{% endblock content %}